# Workflow name
name: Continuous Deployment

# This allows manual start of the pipeline as needed.
on: workflow_dispatch

# The list of jobs to run 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Configure AWS credentials      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

          
      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      # 3. Setup Node
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      # 4. Setup Cache
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 5. Build Angular
      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install --legacy-peer-deps
          npm run build
          
      # 6. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
              args: --acl public-read --follow-symlinks --delete
        env: 
            AWS_S3_BUCKET: dashboard.revords.com
        # run: |
        #   aws s3 sync ./dist/* s3://dashboard.revords.com --delete
          
      # 7. (Optional) Invalidate CloudFront
      - name: Invalidate CloudFront
      
        run: |
          aws cloudfront create-invalidation --distribution-id E23EZL5A1TYJLZ --paths "/*"
